/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP S2 <https://github.com/OpenChargingCloud/WWCP_S2>
 *
 * Licensed under the Affero GPL license, Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/licenses/agpl.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace cloud.charging.open.protocols.S2.Connect
{

    /// <summary>
    /// The one place that generates every secret of S2 Connect, all from the cryptographically
    /// secure <see cref="System.Security.Cryptography.RandomNumberGenerator"/>
    /// (S2 Connect: pairing tokens, challenges, pairing attempt ids, access tokens and
    /// communication tokens "must be generated by a cryptographically secure pseudorandom
    /// number generator"). The methods delegate to the factories of the individual types.
    /// </summary>
    public static class TokenGenerator
    {

        /// <summary>
        /// A new dynamic pairing token (default: 6 characters from the confusion-free alphabet).
        /// </summary>
        /// <param name="Length">The number of characters (at least 4).</param>
        public static PairingToken NewDynamicPairingToken(Int32 Length = 6)
            => PairingToken.NewDynamic(Length);

        /// <summary>
        /// A new static pairing token (default: 8 characters from the confusion-free alphabet).
        /// </summary>
        /// <param name="Length">The number of characters (at least 6).</param>
        public static PairingToken NewStaticPairingToken(Int32 Length = 8)
            => PairingToken.NewStatic(Length);

        /// <summary>
        /// A new HMAC challenge (default: 32 random bytes).
        /// </summary>
        /// <param name="NumberOfBytes">The number of random bytes (at least 32).</param>
        public static HmacChallenge NewChallenge(Int32 NumberOfBytes = HmacChallenge.RecommendedBytes)
            => HmacChallenge.NewRandom(NumberOfBytes);

        /// <summary>
        /// A new pairing attempt identification (24 random bytes, Base64 encoded).
        /// </summary>
        public static PairingAttemptId NewPairingAttemptId()
            => PairingAttemptId.NewRandom();

        /// <summary>
        /// A new access token (default: 32 random bytes).
        /// </summary>
        /// <param name="NumberOfBytes">The number of random bytes (at least 32).</param>
        public static AccessToken NewAccessToken(Int32 NumberOfBytes = AccessToken.RecommendedBytes)
            => AccessToken.NewRandom(NumberOfBytes);

        /// <summary>
        /// A new communication (WebSocket) token (default: 32 random bytes).
        /// </summary>
        /// <param name="NumberOfBytes">The number of random bytes (at least 32).</param>
        public static CommunicationToken NewCommunicationToken(Int32 NumberOfBytes = CommunicationToken.RecommendedBytes)
            => CommunicationToken.NewRandom(NumberOfBytes);

    }

}
