/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP S2 <https://github.com/OpenChargingCloud/WWCP_S2>
 *
 * Licensed under the Affero GPL license, Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/licenses/agpl.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#region Usings

using System.Text.RegularExpressions;

#endregion

namespace cloud.charging.open.protocols.S2
{

    /// <summary>
    /// The common rules of all S2 identifiers (ID.schema.json): a string matching the
    /// pattern [a-zA-Z0-9\-_:]{2,64}. The schema pattern is unanchored, so, following
    /// JSON Schema semantics, any string containing such a run of characters is valid;
    /// identifiers generated by this library are always UUIDs (PLAN.md §3.9).
    /// </summary>
    public static partial class S2_Id
    {

        #region Data

        /// <summary>
        /// The regular expression of ID.schema.json.
        /// </summary>
        public const String SchemaPattern  = "[a-zA-Z0-9\\-_:]{2,64}";

        /// <summary>
        /// The null UUID.
        /// </summary>
        public const String NullUUID       = "00000000-0000-0000-0000-000000000000";

        private static readonly Regex schemaRegExpr = SchemaRegExpr();

        [GeneratedRegex(SchemaPattern, RegexOptions.CultureInvariant)]
        private static partial Regex SchemaRegExpr();

        #endregion

        #region (static) IsValid(Text)

        /// <summary>
        /// Whether the given text is a valid S2 identifier: not null, not white space,
        /// and matching the (unanchored) schema pattern.
        /// </summary>
        /// <param name="Text">A text.</param>
        public static Boolean IsValid(String? Text)
            => !String.IsNullOrWhiteSpace(Text) && schemaRegExpr.IsMatch(Text);

        #endregion

        #region (static) IsUUID(Text)

        /// <summary>
        /// Whether the given text is a UUID in its canonical hyphenated form.
        /// </summary>
        /// <param name="Text">A text.</param>
        public static Boolean IsUUID(String? Text)
            => Text is not null && Guid.TryParseExact(Text, "D", out _);

        #endregion

        #region (static) NewUUID()

        /// <summary>
        /// Create a new time-ordered UUID (version 7) in lower-case hyphenated form.
        /// </summary>
        public static String NewUUID()
            => Guid.CreateVersion7().ToString("D");

        #endregion

    }

}
