/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP S2 <https://github.com/OpenChargingCloud/WWCP_S2>
 *
 * Licensed under the Affero GPL license, Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/licenses/agpl.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#region Usings

using System.Security.Cryptography;
using System.Diagnostics.CodeAnalysis;

#endregion

namespace cloud.charging.open.protocols.S2.Connect
{

    /// <summary>
    /// The one-time access token with which a communication client authenticates its session
    /// initiation (s2-connect-common.yml, AccessToken): random binary data of at least 32 bytes,
    /// standard Base64 encoded on the wire, renewed with every session. The wire text is kept
    /// verbatim so that it can be echoed exactly. <see cref="ToString"/> is redacted; use
    /// <see cref="Value"/> for the Authorization header.
    /// </summary>
    public readonly struct AccessToken : IEquatable<AccessToken>
    {

        #region Data

        /// <summary>
        /// The number of random bytes of a generated token (S2 Connect: "minimum length of 32 bytes").
        /// </summary>
        public const Int32  RecommendedBytes  = 32;

        /// <summary>
        /// The minimal number of decoded bytes accepted when parsing.
        /// </summary>
        public const Int32  MinimumBytes      = 1;

        #endregion

        #region Properties

        /// <summary>
        /// The standard Base64 text as on the wire.
        /// </summary>
        public String                Value    { get; }

        /// <summary>
        /// The decoded binary value.
        /// </summary>
        public ReadOnlyMemory<Byte>  Bytes    { get; }

        /// <summary>
        /// The number of decoded bytes.
        /// </summary>
        public Int32                 Length
            => Bytes.Length;

        #endregion

        #region Constructor(s)

        private AccessToken(String                Text,
                            ReadOnlyMemory<Byte>  Bytes)
        {
            this.Value  = Text;
            this.Bytes  = Bytes;
        }

        #endregion


        #region Documentation

        // s2-connect-common.yml
        //   AccessToken:
        //     description: One-time access token for secure access to the S2 message communication channel.
        //                  It must be renewed every time a client wants to access the S2 message communication
        //                  channel by calling the requestToken endpoint. This token is valid for one time login,
        //                  with a maximum 5 years, and should have a minimum length of 32 bytes.
        //     type:        string
        //     format:      byte
        //
        // S2 Connect 1.0.0, "8A. Response status 200": The access token is random binary data and must be
        // generated by a cryptographically secure pseudorandom number generator and must have a minimum
        // length of 32 bytes. It is encoded using Base64.

        #endregion

        #region (static) FromBytes(Bytes)

        /// <summary>
        /// Create an access token from the given binary value.
        /// </summary>
        /// <param name="Bytes">The binary value (at least one byte).</param>
        public static AccessToken FromBytes(ReadOnlySpan<Byte> Bytes)
        {

            ArgumentOutOfRangeException.ThrowIfLessThan(Bytes.Length, MinimumBytes);

            return new AccessToken(Convert.ToBase64String(Bytes), Bytes.ToArray());

        }

        #endregion

        #region (static) NewRandom(NumberOfBytes = 32)

        /// <summary>
        /// Generate a new random access token from a cryptographically secure generator.
        /// </summary>
        /// <param name="NumberOfBytes">The number of random bytes (at least 32).</param>
        public static AccessToken NewRandom(Int32 NumberOfBytes = RecommendedBytes)
        {

            ArgumentOutOfRangeException.ThrowIfLessThan(NumberOfBytes, RecommendedBytes);

            return FromBytes(RandomNumberGenerator.GetBytes(NumberOfBytes));

        }

        #endregion

        #region (static) Parse    (Text)

        /// <summary>
        /// Parse the given standard Base64 text as an access token.
        /// </summary>
        /// <param name="Text">A Base64 text.</param>
        public static AccessToken Parse(String Text)
        {

            if (TryParse(Text, out var token))
                return token;

            throw new ArgumentException("Invalid Base64 text representation of an access token!", nameof(Text));

        }

        #endregion

        #region (static) TryParse (Text, out AccessToken)

        /// <summary>
        /// Try to parse the given standard Base64 text (with padding, no white space) as an access token.
        /// </summary>
        /// <param name="Text">A Base64 text.</param>
        /// <param name="AccessToken">The parsed access token.</param>
        public static Boolean TryParse(String                                 Text,
                                       [NotNullWhen(true)] out AccessToken    AccessToken)
        {

            AccessToken = default;

            if (String.IsNullOrEmpty(Text) || Text.Length % 4 != 0)
                return false;

            foreach (var c in Text)
            {
                if (!(Char.IsAsciiLetterOrDigit(c) || c is '+' or '/' or '='))
                    return false;
            }

            var buffer = new Byte[Text.Length / 4 * 3];

            if (!Convert.TryFromBase64String(Text, buffer, out var written) || written < MinimumBytes)
                return false;

            AccessToken = new AccessToken(Text, buffer.AsMemory(0, written));
            return true;

        }

        #endregion


        #region ConstantTimeEquals(AccessToken)

        /// <summary>
        /// Compares the binary values of two access tokens in constant time.
        /// </summary>
        /// <param name="AccessToken">An access token to compare with.</param>
        public Boolean ConstantTimeEquals(AccessToken AccessToken)
            => CryptographicOperations.FixedTimeEquals(Bytes.Span, AccessToken.Bytes.Span);

        #endregion


        #region Operator overloading

        /// <summary>
        /// Compares two access tokens for equality.
        /// </summary>
        public static Boolean operator == (AccessToken AccessToken1, AccessToken AccessToken2)
            => AccessToken1.Equals(AccessToken2);

        /// <summary>
        /// Compares two access tokens for inequality.
        /// </summary>
        public static Boolean operator != (AccessToken AccessToken1, AccessToken AccessToken2)
            => !AccessToken1.Equals(AccessToken2);

        #endregion

        #region IEquatable<AccessToken> Members

        /// <summary>
        /// Compares two access tokens for equality.
        /// </summary>
        /// <param name="Object">An access token to compare with.</param>
        public override Boolean Equals(Object? Object)
            => Object is AccessToken token && Equals(token);

        /// <summary>
        /// Compares the binary values of two access tokens for equality (constant time).
        /// </summary>
        /// <param name="AccessToken">An access token to compare with.</param>
        public Boolean Equals(AccessToken AccessToken)
            => ConstantTimeEquals(AccessToken);

        #endregion

        #region (override) GetHashCode()

        /// <summary>
        /// Return the hash code of this object.
        /// </summary>
        public override Int32 GetHashCode()
        {

            var hash = new HashCode();
            hash.AddBytes(Bytes.Span);
            return hash.ToHashCode();

        }

        #endregion

        #region (override) ToString()

        /// <summary>
        /// Return a redacted text representation (the token is a secret).
        /// </summary>
        public override String ToString()
            => Value is null ? "" : $"[access token, {Length} bytes]";

        #endregion

    }

}
