/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP S2 <https://github.com/OpenChargingCloud/WWCP_S2>
 *
 * Licensed under the Affero GPL license, Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/licenses/agpl.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#region Usings

using System.Text;
using System.Text.RegularExpressions;
using System.Security.Cryptography;
using System.Diagnostics.CodeAnalysis;

#endregion

namespace cloud.charging.open.protocols.S2.Connect
{

    /// <summary>
    /// The secret pairing token: a random string of letters and digits issued by the
    /// Responder node, transferred by the end user to the Initiator node, and verified
    /// through the HMAC challenge-response process without ever being sent over the wire
    /// (S2 Connect, "The pairing token, the node ID alias and the pairing code").
    /// Dynamic tokens have at least 4 characters and expire (5 minutes recommended);
    /// static tokens printed on a device have at least 6 characters and never expire.
    /// <see cref="ToString"/> is redacted; use <see cref="Value"/> to display the token.
    /// </summary>
    public readonly partial struct PairingToken : IEquatable<PairingToken>
    {

        #region Data

        [GeneratedRegex(S2ConnectDefaults.DynamicPairingTokenRegExpr, RegexOptions.CultureInvariant)]
        private static partial Regex TokenRegExpr();

        #endregion

        #region Properties

        /// <summary>
        /// The secret text value of the pairing token.
        /// </summary>
        public String   Value                       { get; }

        /// <summary>
        /// The length of the token in characters.
        /// </summary>
        public Int32    Length
            => Value?.Length ?? 0;

        /// <summary>
        /// Whether the token is long enough to be used as a static (never expiring) token.
        /// </summary>
        public Boolean  MeetsStaticRequirement
            => Length >= S2ConnectDefaults.MinStaticPairingTokenLength;

        #endregion

        #region Constructor(s)

        private PairingToken(String Text)
        {
            this.Value = Text;
        }

        #endregion


        #region Documentation

        // S2 Connect 1.0.0, "The pairing token, the node ID alias and the pairing code":
        //
        //   | Type of pairing token | Minimal length | Validity                                   | Regular expression  |
        //   | Dynamic pairing token | 4 characters   | Limited duration, 5 minutes is recommended | ^[0-9a-zA-Z]{4,}$   |
        //   | Static pairing token  | 6 characters   | Indefinitely                               | ^[0-9a-zA-Z]{6,}$   |
        //
        //   The pairing token must be generated by a cryptographically secure pseudorandom number generator.
        //   Note: The pairing token is secret. It is never exchanged; it is only used as input for the
        //   challenge response function.

        #endregion

        #region (static) IsValid(Text)

        /// <summary>
        /// Whether the given text is a valid pairing token: at least four letters or digits.
        /// </summary>
        /// <param name="Text">A text.</param>
        public static Boolean IsValid(String? Text)
            => Text is not null && TokenRegExpr().IsMatch(Text);

        #endregion

        #region (static) Parse    (Text)

        /// <summary>
        /// Parse the given string as a pairing token.
        /// </summary>
        /// <param name="Text">A text representation of a pairing token.</param>
        public static PairingToken Parse(String Text)
        {

            if (TryParse(Text, out var token))
                return token;

            throw new ArgumentException("Invalid text representation of a pairing token!", nameof(Text));

        }

        #endregion

        #region (static) TryParse (Text, out PairingToken)

        /// <summary>
        /// Try to parse the given text as a pairing token.
        /// </summary>
        /// <param name="Text">A text representation of a pairing token.</param>
        /// <param name="PairingToken">The parsed pairing token.</param>
        public static Boolean TryParse(String                                  Text,
                                       [NotNullWhen(true)] out PairingToken    PairingToken)
        {

            if (IsValid(Text))
            {
                PairingToken = new PairingToken(Text);
                return true;
            }

            PairingToken = default;
            return false;

        }

        #endregion

        #region (static) NewDynamic(Length = 6) / NewStatic(Length = 8)

        /// <summary>
        /// Generate a new dynamic pairing token from a cryptographically secure random source,
        /// using the alphabet without easily confused characters (PLAN.md §3.6).
        /// </summary>
        /// <param name="Length">The number of characters (at least 4).</param>
        public static PairingToken NewDynamic(Int32 Length = 6)
        {

            ArgumentOutOfRangeException.ThrowIfLessThan(Length, S2ConnectDefaults.MinDynamicPairingTokenLength);

            return new PairingToken(RandomNumberGenerator.GetString(S2ConnectDefaults.PairingTokenAlphabet, Length));

        }

        /// <summary>
        /// Generate a new static pairing token from a cryptographically secure random source,
        /// using the alphabet without easily confused characters (PLAN.md §3.6).
        /// </summary>
        /// <param name="Length">The number of characters (at least 6).</param>
        public static PairingToken NewStatic(Int32 Length = 8)
        {

            ArgumentOutOfRangeException.ThrowIfLessThan(Length, S2ConnectDefaults.MinStaticPairingTokenLength);

            return new PairingToken(RandomNumberGenerator.GetString(S2ConnectDefaults.PairingTokenAlphabet, Length));

        }

        #endregion


        #region ToBytes()

        /// <summary>
        /// The token as ASCII bytes, the form used as input of the challenge-response function
        /// (S2 Connect: "The pairing token and domain name are strings, which need to be
        /// converted into binary data using the ASCII table").
        /// </summary>
        public Byte[] ToBytes()
            => Encoding.ASCII.GetBytes(Value ?? "");

        #endregion

        #region ConstantTimeEquals(PairingToken)

        /// <summary>
        /// Compares two pairing tokens in constant time.
        /// </summary>
        /// <param name="PairingToken">A pairing token to compare with.</param>
        public Boolean ConstantTimeEquals(PairingToken PairingToken)
            => CryptographicOperations.FixedTimeEquals(ToBytes(), PairingToken.ToBytes());

        #endregion


        #region Operator overloading

        /// <summary>
        /// Compares two pairing tokens for equality.
        /// </summary>
        public static Boolean operator == (PairingToken PairingToken1, PairingToken PairingToken2)
            => PairingToken1.Equals(PairingToken2);

        /// <summary>
        /// Compares two pairing tokens for inequality.
        /// </summary>
        public static Boolean operator != (PairingToken PairingToken1, PairingToken PairingToken2)
            => !PairingToken1.Equals(PairingToken2);

        #endregion

        #region IEquatable<PairingToken> Members

        /// <summary>
        /// Compares two pairing tokens for equality.
        /// </summary>
        /// <param name="Object">A pairing token to compare with.</param>
        public override Boolean Equals(Object? Object)
            => Object is PairingToken token && Equals(token);

        /// <summary>
        /// Compares two pairing tokens for equality (constant time).
        /// </summary>
        /// <param name="PairingToken">A pairing token to compare with.</param>
        public Boolean Equals(PairingToken PairingToken)
            => ConstantTimeEquals(PairingToken);

        #endregion

        #region (override) GetHashCode()

        /// <summary>
        /// Return the hash code of this object.
        /// </summary>
        public override Int32 GetHashCode()
            => Value?.GetHashCode(StringComparison.Ordinal) ?? 0;

        #endregion

        #region (override) ToString()

        /// <summary>
        /// Return a redacted text representation (the token is a secret).
        /// </summary>
        public override String ToString()
            => Value is null ? "" : $"[pairing token, {Length} characters]";

        #endregion

    }

}
