/*
 * Copyright (c) 2014-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP S2 <https://github.com/OpenChargingCloud/WWCP_S2>
 *
 * Licensed under the Affero GPL license, Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/licenses/agpl.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#region Usings

using System.Text;
using System.Security.Cryptography;
using System.Diagnostics.CodeAnalysis;

#endregion

namespace cloud.charging.open.protocols.S2.Connect
{

    /// <summary>
    /// The secret identifier of one pairing attempt, generated by the pairing server, sent as
    /// bearer token with every further request of the attempt, and valid for 15 seconds
    /// (S2 Connect, "3. Response status 200"). <see cref="ToString"/> is redacted; use
    /// <see cref="Value"/> for the Authorization header.
    /// </summary>
    public readonly struct PairingAttemptId : IEquatable<PairingAttemptId>
    {

        #region Properties

        /// <summary>
        /// The secret text value.
        /// </summary>
        public String  Value    { get; }

        /// <summary>
        /// The length in characters.
        /// </summary>
        public Int32   Length
            => Value?.Length ?? 0;

        #endregion

        #region Constructor(s)

        private PairingAttemptId(String Text)
        {
            this.Value = Text;
        }

        #endregion


        #region Documentation

        // s2-connect-pairing.yml
        //   PairingAttemptId:
        //     description: A secret identifier that is generated by the server for each pairing attempt. It is used as
        //                  authentication of the client and to keep track of the client requests through the several
        //                  steps of the pairing process. Once the pairing process is finished (with or without success)
        //                  the identifier can be discarded. The PairingAttemptId is a random string with a minimal length
        //                  of 32 characters. The server must use a cryptographically secure pseudorandom number generator
        //                  to generate the string. The recommended method is to generate 24 random bytes and Base64 encode them.
        //     type:        string
        //     minLength:   32
        //
        //   securitySchemes: pairingAttemptId: type: http, scheme: bearer

        #endregion

        #region (static) IsValid(Text)

        /// <summary>
        /// Whether the given text is a valid pairing attempt identification: at least 32
        /// characters, none of them white space or control characters (it travels as a
        /// bearer token).
        /// </summary>
        /// <param name="Text">A text.</param>
        public static Boolean IsValid(String? Text)
        {

            if (Text is null || Text.Length < S2ConnectDefaults.MinPairingAttemptIdLength)
                return false;

            foreach (var c in Text)
            {
                if (Char.IsWhiteSpace(c) || Char.IsControl(c))
                    return false;
            }

            return true;

        }

        #endregion

        #region (static) Parse    (Text)

        /// <summary>
        /// Parse the given string as a pairing attempt identification.
        /// </summary>
        /// <param name="Text">A text representation of a pairing attempt identification.</param>
        public static PairingAttemptId Parse(String Text)
        {

            if (TryParse(Text, out var id))
                return id;

            throw new ArgumentException("Invalid text representation of a pairing attempt identification!", nameof(Text));

        }

        #endregion

        #region (static) TryParse (Text, out PairingAttemptId)

        /// <summary>
        /// Try to parse the given text as a pairing attempt identification.
        /// </summary>
        /// <param name="Text">A text representation of a pairing attempt identification.</param>
        /// <param name="PairingAttemptId">The parsed pairing attempt identification.</param>
        public static Boolean TryParse(String                                      Text,
                                       [NotNullWhen(true)] out PairingAttemptId    PairingAttemptId)
        {

            if (IsValid(Text))
            {
                PairingAttemptId = new PairingAttemptId(Text);
                return true;
            }

            PairingAttemptId = default;
            return false;

        }

        #endregion

        #region (static) NewRandom()

        /// <summary>
        /// Generate a new pairing attempt identification: 24 random bytes from a cryptographically
        /// secure generator, standard Base64 encoded (32 characters).
        /// </summary>
        public static PairingAttemptId NewRandom()
            => new (Convert.ToBase64String(RandomNumberGenerator.GetBytes(S2ConnectDefaults.PairingAttemptIdRandomBytes)));

        #endregion


        #region ConstantTimeEquals(PairingAttemptId)

        /// <summary>
        /// Compares two pairing attempt identifications in constant time.
        /// </summary>
        /// <param name="PairingAttemptId">A pairing attempt identification to compare with.</param>
        public Boolean ConstantTimeEquals(PairingAttemptId PairingAttemptId)
            => CryptographicOperations.FixedTimeEquals(Encoding.UTF8.GetBytes(Value ?? ""),
                                                       Encoding.UTF8.GetBytes(PairingAttemptId.Value ?? ""));

        #endregion


        #region Operator overloading

        /// <summary>
        /// Compares two pairing attempt identifications for equality.
        /// </summary>
        public static Boolean operator == (PairingAttemptId PairingAttemptId1, PairingAttemptId PairingAttemptId2)
            => PairingAttemptId1.Equals(PairingAttemptId2);

        /// <summary>
        /// Compares two pairing attempt identifications for inequality.
        /// </summary>
        public static Boolean operator != (PairingAttemptId PairingAttemptId1, PairingAttemptId PairingAttemptId2)
            => !PairingAttemptId1.Equals(PairingAttemptId2);

        #endregion

        #region IEquatable<PairingAttemptId> Members

        /// <summary>
        /// Compares two pairing attempt identifications for equality.
        /// </summary>
        /// <param name="Object">A pairing attempt identification to compare with.</param>
        public override Boolean Equals(Object? Object)
            => Object is PairingAttemptId id && Equals(id);

        /// <summary>
        /// Compares two pairing attempt identifications for equality (constant time).
        /// </summary>
        /// <param name="PairingAttemptId">A pairing attempt identification to compare with.</param>
        public Boolean Equals(PairingAttemptId PairingAttemptId)
            => ConstantTimeEquals(PairingAttemptId);

        #endregion

        #region (override) GetHashCode()

        /// <summary>
        /// Return the hash code of this object.
        /// </summary>
        public override Int32 GetHashCode()
            => Value?.GetHashCode(StringComparison.Ordinal) ?? 0;

        #endregion

        #region (override) ToString()

        /// <summary>
        /// Return a redacted text representation (the identification is a secret).
        /// </summary>
        public override String ToString()
            => Value is null ? "" : $"[pairing attempt id, {Length} characters]";

        #endregion

    }

}
